
#name, main, version and api are required
name: WMagicGuns
main: me.hbj233.wmagicguns.WMagicGunsPlugin
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1"
api: ["1.0.0"]
author: HBJ233
depend:
  - KotlinLib